### ISSUE TITLE
[Bug]: GPT3Tokenizer is not using same encoding with gpt-4 and gpt-3.5

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#1171]
### Language

Javascript/Typescript

### Version

latest

### Description

The [GPT3Tokenizer](https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/tokenizers/GPT3Tokenizer.ts#L10) is using `gpt-3-encoder` package, which uses `r50k_base` encoding. However, gpt-4 and gpt-3.5 is using `cl100k_base` encoding. As the major model used with Teams-AI library is gpt-4 and gpt-3.5, using `gpt-3-encoder` by default might cause potential issues.
We need to either update `GPT3Tokenizer` to use `cl100k_base` encoding, or create a new tokenizer for gpt-4/3.5 and set the new tokenizer as the default one.

Reference: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

### Reproduction Steps

```bash
N/A
```

**Comment by Stevenic** [comment]
The issue is there’s not a 3rd party implementation of tiktoken that I’m aware of for JS. Everyone just uses gpt-3-encoder because it’s close enough. Token counting in general (regardless of tiktoken or not) is a rough estimate at best for numerous reasons these days. OpenAI adds all sorts of hidden tokens to the prompt that you can’t easily account for.  It’s best to just overestimate by a small percentage.

**Comment by corinagum** [comment]
https://github.com/niieani/gpt-tokenizer seems like a good alternative.
