### ISSUE TITLE
[Bug]: TeamsAttachmentDownloader - 401 Axios Request 

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#1404]
### Language

Javascript/Typescript

### Version

latest

### Description

A 401 AxiosError is being thrown in `downloadFile` function, when attempting the GET request on `attachment.contentUrl`. A token is being generated, and the current logic is the same prior to merging #1207, hence my suspicion is that the access token is not in the correct format. If this is the case, the bug is probably nested in `getAccessToken` method

NOTE: This is with the updated code in #1403

### Reproduction Steps

```bash
1. Spin up the Cardgazer bot
2. Send the bot a message to construct an adaptive card, with a photo of a form.
3. The code should throw a 401 AxiosError.
...
```

**Comment by corinagum** [comment]
Thanks for filing @lilyydu

**Comment by corinagum** [comment]
Still having trouble with repro-ing this bug, but attempts are ongoing

**Comment by corinagum** [comment]
@chandanrjit I'm hoping to get back to this bug in the next few days -- could you share your stack trace for the error? Thanks!

**Comment by corinagum** [comment]
I have been unable to reproduce this error - I have successfully built the sample, sent an image that returns adaptive card JSON, and even can render that adaptive card:
![image](https://github.com/microsoft/teams-ai/assets/14900841/20a441cb-e73a-4a69-99b2-64488693361e)


My closest guess is that if your API key from OpenAI has expired, the API key is incorrect, or you have run out of credits, the 401 error was because of that. One option to look into would be to check your OpenAI account for usage tracking and see if calls are successfully going through.

Otherwise, if someone could provide a stack trace for this error that could possibly help with a repro.

**Comment by yonggang-xiao** [comment]
I got the same issue:
[onTurnError] unhandled error: AxiosError: Request failed with status code 401

using teams-ai 1.2.1
in TeamsAttachmentDownloader.js file when call
`const response = await this._httpClient.get(attachment.contentUrl, {
                headers,
                responseType: 'arraybuffer'
            });`

**Comment by yonggang-xiao** [comment]
There is no problem when copy & pasted image.
But upload image using "+" will get 401 AxiosError
<img width="205" alt="截屏2024-06-07 17 56 21" src="https://github.com/microsoft/teams-ai/assets/137489864/5c0ae7e4-d8ed-4da7-8a7a-2a05fd7cc18d">
