### ISSUE TITLE
[Bug]: Llama sample's GetLightStatus is inconsistent

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#1522]
### Language

Javascript/Typescript

### Version

latest

### Description

`getLightStatus` is currently a prompt function which doesn't seem to work with Llama well. Should be updated to be an action.

### Reproduction Steps

```bash
1.
2.
3.
...
```

**Comment by Stevenic** [comment]
At a minimum, you need to use instruction tuned models that have been finetuned to follow instructions. Instruction tuned models are base models that have been fine tuned to follow instructions. LLaMA out of the box isn't tuned to follow instructions so it's not going to be reliable.

In addition to instruction tuning, we're now seeing models that have been specifically tuned for function calling. These models should work best. Octopus-v2 is one such model that I'm excited to try as it's a 2-bit model so able to run on a phone:

https://huggingface.co/NexaAIDev/Octopus-v2

The other thing on this front is the use of grammars:

https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md

These are BNF rules you can define that force the model to always return JSON and even can force it to always follow a given schema. You need to pair grammars with good models that have been tuned for instruction following at a minimum otherwise the model will resist the grammar.

**Comment by corinagum** [comment]
I have moved this work item from in progress to triaged - for now, with the 'limits' explained by stevenic above, Llama model without tuning will mean that the sample has limited functionality. Ideally in the future this should be converted to the twenty questions sample to avoid confusion.
