### ISSUE TITLE
[Feature Request]: use managed identity in Python bot

### ISSUE THREAD

**Issue by frankqianms** [microsoft/teams-ai#1615]
### Scenario

According to [this doc](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp#:~:text=The%20Java%20version%20of%20the%20Bot%20Framework%20SDK%20only%20supports%20multi%2Dtenant%20bots.%20The%20Python%20version%20of%20the%20Bot%20Framework%20SDK%20supports%20multi%2Dtenant%20and%20single%2Dtenant%20bots.%20The%20C%23%20and%20JavaScript%20versions%20support%20all%20three%20application%20types%20for%20managing%20the%20bot%27s%20identity.), the Python version of the Bot Framework SDK supports multi-tenant and single-tenant bots. Since Teams-ai depends on Bot Framework SDK, Python bots here do not support managed identity either. 

### Solution

Please let Python bots support managed identity.

**Comment by aacebo** [comment]
@BMS-geodev

**Comment by BMS-geodev** [comment]
test comment

**Comment by aacebo** [comment]
here is an example of using cert based authentication via `@azure/identity` with BF https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/84.bot-authentication-certificate. Since we wrap bot framework any auth enhancements would need to take place in their SDK for us to utilize.
