### ISSUE TITLE
[Bug]: EmbeddingsResponse class output property should be List[List[float]] instead of List[List[int]]

### ISSUE THREAD

**Issue by yikwen** [microsoft/teams-ai#1646]
### Language

Python

### Version

latest

### Description

The EmbeddingsResponse class declared in teams.ai.embeddings has a type of `Optional[Union[List[List[int]], str]]`. Given that embeddings are floating point numbers, the type should be probably be `Optional[Union[List[List[float]], str]]`

### Reproduction Steps

```bash
1.None
```

**Comment by yikwen** [comment]
For comparison, the equivalent Javascript interface definition uses number[][]

```
export interface EmbeddingsResponse {
...
    /**
     * Optional. Embeddings for the given inputs.
     */
    output?: number[][];
...
}
```

**Comment by lilyydu** [comment]
Hi @yikwen, great catch. Updating to float will also match the [dotnet implementation](https://github.com/microsoft/teams-ai/blob/main/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Embeddings/EmbeddingsResponse.cs). Please feel free to open up a PR to update this, otherwise I will get to it sometime this week!

**Comment by yikwen** [comment]
@lilyydu I've created pull request #1677 . Since this is my first time (ever) contributing to an open-source project, I hope I'm doing it right.
