### ISSUE TITLE
[Dev support]: Citations when using Azure AI Search (or equivalent external data source) for augmentations

### ISSUE THREAD

**Issue by yikwen** [microsoft/teams-ai#1693]
Please be sure to check the Discussions Q&A section before filing a new question.

## Is it possible to generate citations from context used to generate an answer?
1. Referring to the "Chat with Azure AI Search Data" Javascript sample here: https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/g.datasource-azureAISearch
2. I've made a Python equivalent of the bot, which uses Azure AI Search as a data source for augmentations and also performs actions
3. However, the context used for answering questions is not currently rendered as references / citations like the Azure OpenAI On Your Data here https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/h.datasource-azureOpenAI
4. Is there a way to structure the response message such that it provides references when the data source is used as augmentation?

## What you have tried already

Rewrote `AzureAISearchDataSource.ts` in Python. Works, but no citations.

**Comment by corinagum** [comment]
For Python, we are waiting for a couple of bug fixes that another customer has provided a PR for. Please track: https://github.com/microsoft/teams-ai/pull/1670
and: https://github.com/microsoft/teams-ai/pull/1697

Otherwise, you may need to enable public preview on your teams (either at the user or administrator level) in order to see citations.
