### ISSUE TITLE
[Bug]: Feed back loop and citation features do not work both with JS and PY SDK

### ISSUE THREAD

**Issue by frankqianms** [microsoft/teams-ai#1833]
### Language

Javascript/Typescript

### Version

latest

### Description

For JS SDK, feed back loop and citation features do not work by following the [CONCEPTS doc](https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/POWERED-BY-AI.md). 
For PY SDK, no docs can follow. By following similar steps as JS doc shows, these two features do not work either.

### Reproduction Steps

```bash
1. 
2.
3.
...
```

**Comment by corinagum** [comment]
@frankqianms these features are not yet on public ring - are you using R4? It should be available within a week or two on all rings. Users would need to be using at least developer preview or lower rings. 
I have tested this on JS yesterday and things are working on R0. 

Otherwise, more information on what problems you are running into would be helpful

**Comment by corinagum** [comment]
@frankqianms please provide the raw request and response of the bot activity so that we can take a look.

**Comment by frankqianms** [comment]
@corinagum Thanks for your remind. After switching to R0, feedback loop worked well both on JS and PY. But for citations, it didn't work for me. I wonder if it was related to this issue: https://github.com/microsoft/teams-ai/issues/1590.

I tested these using sample [g.datasource-azureAISearch](https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/g.datasource-azureAISearch) after deleting [this line](https://github.com/microsoft/teams-ai/blob/06d80f4a6dacfe5bbd34828fe3c13581194cbb9f/js/samples/04.ai-apps/g.datasource-azureAISearch/src/app.ts#L86).
