### ISSUE TITLE
[Dev support]: How to count the number of tokens in each conversation

### ISSUE THREAD

**Issue by jamiesun** [microsoft/teams-ai#2062]
## Question

How to count the number of tokens in each conversation

- Include user input
- Include system prompts
- Include history
- Include response content

How to get the total number of tokens at a time

**Comment by SubbaReddi** [comment]
@jamiesun : You may need to refere following to count the number of tokens: https://github.com/openai/tiktoken

**Comment by corinagum** [comment]
@jamiesun in our library, we use the tokenizer module to help calculate number of tokens based on the model. The package dependency is `gpt-tokenizer`. The tokenizer is used internally in the planner to manage the amount of tokens being sent to the LLM using the max-tokens setting. 
Tracking token usage unfortunately won't be simple or 100% exact, but you could potentially do something like the following: 

```typescript
app.turn('afterTurn', async (ctx, state) => {
    const tokenizer = new GPTTokenizer();
    let tokens = 0;

    for (const message of state.conversation['sequence_history']) {
        if (!message.content) continue;
        tokens += tokenizer.encode(message.content).length;        
    }
});
```

**Comment by jamiesun** [comment]
@corinagum  But there will be a system prompt for each round of dialogue, and through the dynamic generation of the template, I didn't find a way to count the tokens of this content

**Comment by Benjiiim** [comment]
@jamiesun, have you been able to implement something useful on your end?
I was thinking of improving @corinagum example by adding a way to distinct input tokens from output tokens (from my understanding, any content appearing after the last occurence of context.activity.text might be considered as output tokens).
But I'm still looking for a way to dynamically add the system prompt token count as well or any internal calls done by the library.
Thanks a lot

**Comment by Benjiiim** [comment]
The ability to estimate LLM token usage for each turn remains a critical need for the project I’m working on. To provide some context, this project is a multi-tenant ISV application published in the store, and we need to track/estimate the tokens consumed per tenant. This data will support licensing and cost allocation purposes and may eventually be used to enforce throttling policies if required.

In our setup, we use tools augmentation with a single prompt.  

Based on @corinagum’s suggestion, I’m considering implementing the logic within the `afterTurn` event. Here’s the approach I have in mind:

1. **Target only message activities:** Ensure the logic applies exclusively to activities of type `message`.

2. **Count assistant tokens correctly:** The tokens from the last assistant entry in `planner_history` should be classified as output tokens rather than input tokens.

3. **Incorporate prompt-related tokens:** Add the input token count for:
   - The static prompt content (from `skprompt.txt` and `actions.json`).
   - The tokens added after prompt variables and functions evaluations.

4. **Handle tool-related interactions:** 
   - If the second-to-last entry in `planner_history` has the `tool` role, identify the last assistant entry preceding it.
   - Estimate the input tokens for this "internal call" based on the preceding history rows, along with the prompt/actions definition token counts (acknowledging potential omissions if earlier rows were truncated due to `max_input_tokens` limits).
   - Account for output tokens by tokenizing the content of the `action_calls` array.

Does this approach seems correct to you?
Have you implemented something different on your end @jamiesun?
I’d appreciate feedback or suggestions to refine this further.
Thanks a lot
