### ISSUE TITLE
[Bug]: teams-ai/python/samples/06.auth.oauth.bot /README.md not sufficient enough

### ISSUE THREAD

**Issue by DireWolfCoder** [microsoft/teams-ai#2206]
### Language

Python

### Version

latest

### Description

[teams-ai](https://github.com/microsoft/teams-ai/tree/main)/[python](https://github.com/microsoft/teams-ai/tree/main/python)/[samples](https://github.com/microsoft/teams-ai/tree/main/python/samples)/[06.auth.oauth.bot](https://github.com/microsoft/teams-ai/tree/main/python/samples/06.auth.oauth.bot)
/README.md

I can't seem to successfully run this code with the current instructions. 
Updated the .env with newly created app reg creds. But when running f5 it opens the chat in teams yet getting no answers or errors to any messages. I recon it has something to do with the app registration settings as they are not specified. 

Does it work with ngrok or only botframework emulator? How to run botframework emulator in that case?
Why is poetry needed? additional details. Step 5 is really unclear. Do you want the enduser to run f5 whilst in the upper samples repository? wouldn't it have difficulty know which app to run?

step 7? what sample? 

### Reproduction Steps

```bash
1.
2.
3.
...
```

**Comment by Nivedipa-MSFT** [comment]
@DireWolfCoder - Thank you for your inquiry about your Teams app development issue! We will test this and update you soon.

**Comment by corinagum** [comment]
Step 5: It's telling you to open a new window of just the sample (as opposed to having VS code open at the root of the repository)
Step 7: Make sure you're signed into your M365 account etc. in the window for the sample. For example, if you had the root of the repository and the sample directory open and login in the repository window, sometimes the login information won't propagate to other windows (the sample window) immediately.

[poetry](https://python-poetry.org/docs/) is the package manager used for the Python section of this repo. You need to run `poetry run build` to build the code in the python folder.

You can [use ngrok or bot framework emulator to test](https://github.com/microsoft/teams-ai/tree/main/getting-started/OTHER), but you won't have access to the Teams features which is why we recommend Teams Toolkit (TTK).

Please verify with your Teams admin that the RSC permissions from the manifest are permitted in the Teams admin settings.

I'll update the readme a little for clarity.

@Nivedipa-MSFT did you run into any issues running the sample?

**Comment by corinagum** [comment]
FYI I tested both this sample and the JS sample, and the SSO popup never shows for both. This is a Teams client issue, so I am investigating internally with the client team.
