### ISSUE TITLE
OpenAI http client

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#447]
@aacebo please add more details to the task

**Comment by blackchoey** [comment]
One question to this task: can we wrap the OpenAI package to provide strong type, instead of writing from scratch?

**Comment by aacebo** [comment]
This work adds an Http Client to the codebase for handling interactions with `OpenAI`. I explored using their python SDK https://github.com/openai/openai-python but it was nearly impossible to use for a few reasons:
1. it does not come with typings 
2. it is a single instance global implementation, our SDK uses multiple instances since you could potentially have a bot that calls many differnet LLM's, like **Azure OpenAI**, **OpenAI**, and **Bard**. Using their SDK would require us to not only add typings for it but also it would not support a bot that had to call two different **OpenAI** sources like **Azure** and **OpenAI**.
