### ISSUE TITLE
ConversationHistory class

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#448]
@aacebo can you add more details to the task?

**Comment by aacebo** [comment]
This deviation is being explored so that we can more reliably query the conversation history. The linked PR implements a new method that improves the handling of conversation history by:
1. adding the history class instance to the `ConversationState`, making it so the user doesn't need to import and use a static class to interface with the conversations history like you currently do in the other language implementations. This will cut down on unnecessary imports that will make boilerplate simpler.
2. makes interactions with the history more structured and consistent. Currently in the other languages the conversation history is just an array of strings and we use loose logic like "find the last string containing `[SAY]`" to query it. This logic is flimsy and easily broken if the assistant/user uses those keywords in their messages. To fix this the linked PR adds a `Message` class that extends the `OpenAI Message Structure` https://platform.openai.com/docs/guides/gpt/chat-completions-api so that our history queries are more uniform and reliable.
